[package]
name = "rust-shiori-macros"
version = "0.1.0"
authors = ["AlphaModder"]
edition = "2018"
publish = false # for now

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["derive"]}
quote = "0.6"
proc-macro2 = "0.4"


