color = { }

function color.fromhex(hex)
    if type(hex) ~= "string" then return nil end
    local r, g, b = hex:match("#(%x%x)(%x%x)(%x%x)")
    color.fromrgb(tonumber(r, 16) / 255, tonumber(g, 16) / 255, tonumber(b, 16) / 255)
end

function color.fromrgb(r, g, b)
    if type(r) ~= "number" or type(g) ~= "number" or type(b) ~= "number" then return nil end
    return { r = r, g = g, b = b }
end

local colors = {
    aliceblue = color.fromhex("#f0f8ff"),
    antiquewhite = color.fromhex("#faebd7"),
    aqua = color.fromhex("#00ffff"),
    aquamarine = color.fromhex("#7fffd4"),
    azure = color.fromhex("#f0ffff"),
    beige = color.fromhex("#f5f5dc"),
    bisque = color.fromhex("#ffe4c4"),
    black = color.fromhex("#000000"),
    blanchedalmond = color.fromhex("#ffebcd"),
    blue = color.fromhex("#0000ff"),
    blueviolet = color.fromhex("#8a2be2"),
    brown = color.fromhex("#a52a2a"),
    burlywood = color.fromhex("#deb887"),
    cadetblue = color.fromhex("#5f9ea0"),
    chartreuse = color.fromhex("#7fff00"),
    chocolate = color.fromhex("#d2691e"),
    coral = color.fromhex("#ff7f50"),
    cornflowerblue = color.fromhex("#6495ed"),
    cornsilk = color.fromhex("#fff8dc"),
    crimson = color.fromhex("#dc143c"),
    cyan = color.fromhex("#00ffff"),
    darkblue = color.fromhex("#00008b"),
    darkcyan = color.fromhex("#008b8b"),
    darkgoldenrod = color.fromhex("#b8860b"),
    darkgray = color.fromhex("#a9a9a9"),
    darkgreen = color.fromhex("#006400"),
    darkgrey = color.fromhex("#a9a9a9"),
    darkkhaki = color.fromhex("#bdb76b"),
    darkmagenta = color.fromhex("#8b008b"),
    darkolivegreen = color.fromhex("#556b2f"),
    darkorange = color.fromhex("#ff8c00"),
    darkorchid = color.fromhex("#9932cc"),
    darkred = color.fromhex("#8b0000"),
    darksalmon = color.fromhex("#e9967a"),
    darkseagreen = color.fromhex("#8fbc8f"),
    darkslateblue = color.fromhex("#483d8b"),
    darkslategray = color.fromhex("#2f4f4f"),
    darkslategrey = color.fromhex("#2f4f4f"),
    darkturquoise = color.fromhex("#00ced1"),
    darkviolet = color.fromhex("#9400d3"),
    deeppink = color.fromhex("#ff1493"),
    deepskyblue = color.fromhex("#00bfff"),
    dimgray = color.fromhex("#696969"),
    dimgrey = color.fromhex("#696969"),
    dodgerblue = color.fromhex("#1e90ff"),
    firebrick = color.fromhex("#b22222"),
    floralwhite = color.fromhex("#fffaf0"),
    forestgreen = color.fromhex("#228b22"),
    fuchsia = color.fromhex("#ff00ff"),
    gainsboro = color.fromhex("#dcdcdc"),
    ghostwhite = color.fromhex("#f8f8ff"),
    gold = color.fromhex("#ffd700"),
    goldenrod = color.fromhex("#daa520"),
    gray = color.fromhex("#808080"),
    green = color.fromhex("#008000"),
    greenyellow = color.fromhex("#adff2f"),
    grey = color.fromhex("#808080"),
    honeydew = color.fromhex("#f0fff0"),
    hotpink = color.fromhex("#ff69b4"),
    indianred = color.fromhex("#cd5c5c"),
    indigo = color.fromhex("#4b0082"),
    ivory = color.fromhex("#fffff0"),
    khaki = color.fromhex("#f0e68c"),
    lavender = color.fromhex("#e6e6fa"),
    lavenderblush = color.fromhex("#fff0f5"),
    lawngreen = color.fromhex("#7cfc00"),
    lemonchiffon = color.fromhex("#fffacd"),
    lightblue = color.fromhex("#add8e6"),
    lightcoral = color.fromhex("#f08080"),
    lightcyan = color.fromhex("#e0ffff"),
    lightgoldenrodyellow = color.fromhex("#fafad2"),
    lightgray = color.fromhex("#d3d3d3"),
    lightgreen = color.fromhex("#90ee90"),
    lightgrey = color.fromhex("#d3d3d3"),
    lightpink = color.fromhex("#ffb6c1"),
    lightsalmon = color.fromhex("#ffa07a"),
    lightseagreen = color.fromhex("#20b2aa"),
    lightskyblue = color.fromhex("#87cefa"),
    lightslategray = color.fromhex("#778899"),
    lightslategrey = color.fromhex("#778899"),
    lightsteelblue = color.fromhex("#b0c4de"),
    lightyellow = color.fromhex("#ffffe0"),
    lime = color.fromhex("#00ff00"),
    limegreen = color.fromhex("#32cd32"),
    linen = color.fromhex("#faf0e6"),
    magenta = color.fromhex("#ff00ff"),
    maroon = color.fromhex("#800000"),
    mediumaquamarine = color.fromhex("#66cdaa"),
    mediumblue = color.fromhex("#0000cd"),
    mediumorchid = color.fromhex("#ba55d3"),
    mediumpurple = color.fromhex("#9370db"),
    mediumseagreen = color.fromhex("#3cb371"),
    mediumslateblue = color.fromhex("#7b68ee"),
    mediumspringgreen = color.fromhex("#00fa9a"),
    mediumturquoise = color.fromhex("#48d1cc"),
    mediumvioletred = color.fromhex("#c71585"),
    midnightblue = color.fromhex("#191970"),
    mintcream = color.fromhex("#f5fffa"),
    mistyrose = color.fromhex("#ffe4e1"),
    moccasin = color.fromhex("#ffe4b5"),
    navajowhite = color.fromhex("#ffdead"),
    navy = color.fromhex("#000080"),
    oldlace = color.fromhex("#fdf5e6"),
    olive = color.fromhex("#808000"),
    olivedrab = color.fromhex("#6b8e23"),
    orange = color.fromhex("#ffa500"),
    orangered = color.fromhex("#ff4500"),
    orchid = color.fromhex("#da70d6"),
    palegoldenrod = color.fromhex("#eee8aa"),
    palegreen = color.fromhex("#98fb98"),
    paleturquoise = color.fromhex("#afeeee"),
    palevioletred = color.fromhex("#db7093"),
    papayawhip = color.fromhex("#ffefd5"),
    peachpuff = color.fromhex("#ffdab9"),
    peru = color.fromhex("#cd853f"),
    pink = color.fromhex("#ffc0cb"),
    plum = color.fromhex("#dda0dd"),
    powderblue = color.fromhex("#b0e0e6"),
    purple = color.fromhex("#800080"),
    red = color.fromhex("#ff0000"),
    rosybrown = color.fromhex("#bc8f8f"),
    royalblue = color.fromhex("#4169e1"),
    saddlebrown = color.fromhex("#8b4513"),
    salmon = color.fromhex("#fa8072"),
    sandybrown = color.fromhex("#f4a460"),
    seagreen = color.fromhex("#2e8b57"),
    seashell = color.fromhex("#fff5ee"),
    sienna = color.fromhex("#a0522d"),
    silver = color.fromhex("#c0c0c0"),
    skyblue = color.fromhex("#87ceeb"),
    slateblue = color.fromhex("#6a5acd"),
    slategray = color.fromhex("#708090"),
    slategrey = color.fromhex("#708090"),
    snow = color.fromhex("#fffafa"),
    springgreen = color.fromhex("#00ff7f"),
    steelblue = color.fromhex("#4682b4"),
    tan = color.fromhex("#d2b48c"),
    teal = color.fromhex("#008080"),
    thistle = color.fromhex("#d8bfd8"),
    tomato = color.fromhex("#ff6347"),
    turquoise = color.fromhex("#40e0d0"),
    violet = color.fromhex("#ee82ee"),
    wheat = color.fromhex("#f5deb3"),
    white = color.fromhex("#ffffff"),
    whitesmoke = color.fromhex("#f5f5f5"),
    yellow = color.fromhex("#ffff00"),
    yellowgreen = color.fromhex("#9acd32"),
}

function color.fromname(name)
    return colors[name]
end

function color.from(...)
    color = nil
    try = {color.fromrgb, color.fromhex, color.fromname}
    for _, f in ipairs(try) do
        if color == nil then color == f(...) end
    end
    return color
end

for n, c in pairs(colors)
    color[n] = c
end

return color